### ISSUE TITLE
过度翻译

### ISSUE THREAD

**Issue by dragon-archer** [MicrosoftDocs/windowsserverdocs.zh-cn#10]
在cmd内置的start命令的帮助文档中（即通过`start /?`或`help start`显示的内容），关于start的用法示例有过度翻译，以下为有关部分及上下文的内容：
```text
这两个进程可被进一步限制在相同 NUMA 节点内的指定处理器
上运行。在以下示例中，application1 在
节点的两个低位处理器上运行，而 application2
在该节点的其后两个处理器上运行。该示例假定指定节点至少具有四个逻辑处理器。请注意，节点号可更改为该计算机的任何有效节点
号，
而无需更改关联掩码。

    start /NODE 1 /AFFINITY 0x3 application1.exe
    启动 /NODE 1 /AFFINITY 0xc application2.exe

如果命令扩展被启用，通过命令行或 START 命令的外部命令
调用会如下改变:
```
其中`start`作为命令名不需要被翻译为`启动`，尤为奇怪的是在紧邻的两行中只有一个`start`被翻译为`启动`

备注：Windows版本：10.0.19041.153

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/zh-cn/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @dragon-archer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@dragon-archer

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队

**Comment by dragon-archer** [comment]
你好，@CeciAc
此问题发生于windows10的cmd.exe中关于start命令的帮助文档（即使用`help start`或`start /?`输出的信息），而非docs.microsoft.com中的帮助文档，因此应该不是机器翻译的问题
