### ISSUE TITLE
远程桌面后无线网络断开

### ISSUE THREAD

**Issue by liloong** [MicrosoftDocs/windowsserverdocs.zh-cn#11]
[在此处输入反馈]
从A计算机远程桌面到B计算机时，刚刚连接上B计算机，B的无线网络就断开了 ，A电脑提示：
你的远程桌面服务会话已结束。
到远程计算机的连接已丢失，可能是因为网络连接问题。请尝试重新连接到远程计算机。如果问题仍然存在，请联系网络管理员或技术支持。

此时B电脑需要连续认证两次才能正常登陆到系统，不知道具体是什么原因引起的，网络我看了是没问题，B电脑的网络断开后也没有自动重连

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8297a64c-7371-8c72-f4ec-31fab20d2d04
* Version Independent ID: ed865ce7-07c6-1ddd-a201-53ffc1c05997
* Content: [远程笔记本电脑从无线网络断开连接](https://docs.microsoft.com/zh-cn/windows-server/remote/remote-desktop-services/troubleshoot/remote-laptop-disconnects-wireless-network)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/troubleshoot/remote-laptop-disconnects-wireless-network.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/remote/remote-desktop-services/troubleshoot/remote-laptop-disconnects-wireless-network.md)
* GitHub Login: @kaushika-msft
* Microsoft Alias: **delhan**

**Comment by srvbpigh** [comment]
Hello, @liloong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @liloong 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
