### ISSUE TITLE
some translate issue

### ISSUE THREAD

**Issue by liurunliang** [MicrosoftDocs/windowsserverdocs.zh-cn#12]
in "目前 ReFS 上未提供以下功能：" and “ReFS 上仅提供以下功能：“ section
all No(否) were replace with Yes(是)
and  “ReFS 上仅提供以下功能：“  should be "“以下功能仅在ReFS 上提供：“"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1239e469-71b9-faa2-9e4c-2999bbb06e87
* Version Independent ID: 5461ce26-c20b-4a04-692f-1a3721bb96f5
* Content: [复原文件系统 (ReFS) 概述](https://docs.microsoft.com/zh-cn/windows-server/storage/refs/refs-overview#the-following-features-are-unavailable-on-refs-at-this-time)
* Content Source: [WindowsServerDocs/storage/refs/refs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/storage/refs/refs-overview.md)
* Product: **windows-server**
* Technology: **storage-file-systems**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by srvbpigh** [comment]
Hello, @liurunliang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @liurunliang 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
