### ISSUE TITLE
WS08和WVista

### ISSUE THREAD

**Issue by Linyixuan10** [MicrosoftDocs/windowsserverdocs.zh-cn#16]
既然这里有WindowsServer2008，那不能不把WindowsVista也写在上面啊！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5148ebad-44a0-b14a-d65c-e51650ce4197
* Version Independent ID: ceb3e4c3-ccc3-b75a-ccb1-235ad1a22469
* Content: [KMS 客户端安装密钥](https://docs.microsoft.com/zh-cn/windows-server/get-started/kmsclientkeys#feedback)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @Linyixuan10
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Linyixuan10

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4282
非常感谢你对我们的文章作出的贡献。   

深深的祝福，  

Microsoft DOCS International Team
