### ISSUE TITLE
参考链接错误

### ISSUE THREAD

**Issue by Tiaonmmn** [MicrosoftDocs/windowsserverdocs.zh-cn#17]
了解 Active Directory一节中“Active Directory 复制技术”指向的链接应为https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc776877(v=ws.10)。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9bb772ec-10a8-1c86-8af7-5e1d51912866
* Version Independent ID: 743875a3-e418-d81f-1a70-474a3471bfcb
* Content: [Active Directory 域服务概述](https://docs.microsoft.com/zh-cn/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @Tiaonmmn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Tiaonmmn

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by Tiaonmmn** [comment]
本文“了解 Active Directory”一节中有关“Active Directory 复制技术”错误地与“域控制器角色”采用了相同的参考链接。根据文章内容描述，前者的正确链接应为https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc776877(v=ws.10)。

**Comment by illfated** [comment]
(Ref. Pull Request https://github.com/MicrosoftDocs/windowsserverdocs/pull/4370)

**Comment by V-vafune** [comment]
你好，@Tiaonmmn  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  

Microsoft DOCS International Team
