### ISSUE TITLE
某些术语不应翻译成中文

### ISSUE THREAD

**Issue by Tiaonmmn** [MicrosoftDocs/windowsserverdocs.zh-cn#18]
“还原以前版本的虚拟域控制器 VHD 而不进行系统状态数据备份”节中步骤2："...... 在注册表编辑器中，展开以下路径： HKEY_本地_计算机\SYSTEM\CurrentControlSet\Services\NTDS\参数。查找名为 " DSA 先前还原计数" 的值。...... "，此处不应翻译成中文，应对部分内容使用英文：“...... 在注册表编辑器中，展开以下路径： HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NTDS\Parameters。查找名为 " DSA Previous Restore Count" 的值。...... ”，以免不知所云。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14177295-09b9-1a2b-a010-815feb054638
* Version Independent ID: cf8b0510-7e91-737b-5164-f59da19f8529
* Content: [使用 Hyper-v 虚拟化域控制器](https://docs.microsoft.com/zh-cn/windows-server/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controllers-hyper-v#to-restore-a-previous-version-of-a-virtual-domain-controller-vhd-without-system-state-data-backup)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controllers-hyper-v.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controllers-hyper-v.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @Tiaonmmn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
你好，@tiaonmmn，

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队

cc @nokura
