### ISSUE TITLE
the demo git repository have moved, do you want user Azure to instead of ADFS?

### ISSUE THREAD

**Issue by hellohongfu** [MicrosoftDocs/windowsserverdocs.zh-cn#19]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f4866bff-5947-4b24-7958-94a8164b814a
* Version Independent ID: 3d5611d1-df23-90de-cc1b-81862d2f39e4
* Content: [使用 OpenID Connect 和 AD FS 2016 及更高版本构建 web 应用程序](https://docs.microsoft.com/zh-cn/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @hellohongfu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hellohongfu 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @hellohongfu , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hellohongfu 
If you've used Docs in a language other than English, you may have used a feature that allowed you to hover over phrases in some localized articles to view their English translation. Unfortunately, this feature does not meet accessibility guidelines and has been removed from the site. We're working on an improved and fully accessible replacement, so stay tuned.
Kind regards,
Microsoft DOCS International Team
