### ISSUE TITLE
版本号错误

### ISSUE THREAD

**Issue by CreeperKong** [MicrosoftDocs/windowsserverdocs.zh-cn#2]
[在此处输入反馈]
文档中，Server系统的LTSC，应是2019而不是2012

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fc9df0c0-db17-3226-b734-59ebd27fa212
* Version Independent ID: 5b7ddecc-b700-9726-30af-bda0989146e2
* Content: [KMS 客户端安装密钥](https://docs.microsoft.com/zh-cn/windows-server/get-started/kmsclientkeys)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @CreeperKong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
您好，@CreeperKong
謝謝您的寶貴意見。 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。 
順頌時祺 
Microsoft DOCS 國際小組
