### ISSUE TITLE
我在Windows Server 2019 Standard安装Windows Server Admin后出现问题

### ISSUE THREAD

**Issue by TANG617** [MicrosoftDocs/windowsserverdocs.zh-cn#20]
我无法在提供的url上组织配置。打开浏览器，没有证书选择，只有登录框，输入服务器的admin账号密码，只显示"你没有访问此站点的权限。请联系你的管理员。"
我在Windows 10尝试安装，配置Windows Server Admin再添加服务器，但是在账号登陆时出现问题，提示“凭证无效”
![image](https://user-images.githubusercontent.com/24967943/84557461-fdcf3380-ad5d-11ea-808a-98152dd70525.png)
求解，是我Windows Server的用户配置没对吗？微软的帮助文档没有提及这种情况
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6eeacf83-f081-d3ac-2d08-60bf6acde0a4
* Version Independent ID: 20153ee2-be3c-5a77-3fba-0b5bfe763bec
* Content: [Windows 管理中心入门](https://docs.microsoft.com/zh-cn/windows-server/manage/windows-admin-center/use/get-started)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by srvbpigh** [comment]
Hello, @TANG617
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@TANG617， 

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队
