### ISSUE TITLE
哪个版本支持Windows Server2012

### ISSUE THREAD

**Issue by yuchuan1943** [MicrosoftDocs/windowsserverdocs.zh-cn#4]
希望能列出支持Windows Server2012的版本列表

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center 概述](https://docs.microsoft.com/zh-cn/windows-server/manage/windows-admin-center/overview#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by lichasu** [comment]
你好，@yuchuan1943 

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。

如果你有任何与文档相关的反馈，请通过此渠道进行记录。

我们非常感谢你对我们的文章的贡献。

Microsoft DOCS 国际团队
