### ISSUE TITLE
iOS	iTunes 商店中的 iOS 客户端	链接打不开

### ISSUE THREAD

**Issue by jellydong** [MicrosoftDocs/windowsserverdocs.zh-cn#6]
iOS	iTunes 商店中的 iOS 客户端	在 iOS 上开始使用远程桌面客户端，无法打开？
App Store中也搜索不到Microsoft Remote Desktop,请问现在使用什么软件远程Windows？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [远程桌面客户端](https://docs.microsoft.com/zh-cn/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @jellydong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jellydong** [comment]
> Hello, @jellydong
> 
> Thank you for your feedback.
> 
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards,
> Microsoft DOCS International Team

Web site (https://apps.apple.com/app/microsoft-remote-desktop/id714464092) can be opened, just is my network problems.I'm sorry.
But I wonder if you have an IOS version of Microsoft Remote Desktop?If I want to use iPad remote Windows does Microsoft have official software?Like the Microsoft Remote Desktop for android

**Comment by CeciAc** [comment]
Hello, @jellydong

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
