### ISSUE TITLE
此处“群集”应更改为“簇”

### ISSUE THREAD

**Issue by loveGEM** [MicrosoftDocs/windowsserverdocs.zh-cn#7]
ReFS 支持 4K 和 64K 的群集大小。 4K 是针对大多数部署的建议的群集大小，但 64K 群集适合于大型的、顺序 IO 工作负载。应改为ReFS 支持 4K 和 64K 的簇大小。 4K 是针对大多数部署的建议的簇大小，但 64K 簇适合于大型的、顺序 IO 工作负载。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eb95c569-f9ad-8e2d-3423-2c9629e65b72
* Version Independent ID: e2a4c64a-97c0-b310-2e47-d0c348a8ead7
* Content: [复原文件系统 (ReFS) 概述](https://docs.microsoft.com/zh-cn/windows-server/storage/refs/refs-overview#feedback)
* Content Source: [WindowsServerDocs/storage/refs/refs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/blob/live/WindowsServerDocs/storage/refs/refs-overview.md)
* Product: **windows-server**
* Technology: **storage-file-systems**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by srvbpigh** [comment]
Hello, @loveGEM
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@loveGEM  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/windows-server/storage/refs/refs-overview#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
